package com.neuedu.pojo;

import java.util.Date;

public class Logaspect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logaspect.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logaspect.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logaspect.messs
     *
     * @mbg.generated
     */
    private String messs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logaspect.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logaspect.id
     *
     * @return the value of logaspect.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logaspect.id
     *
     * @param id the value for logaspect.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logaspect.userid
     *
     * @return the value of logaspect.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logaspect.userid
     *
     * @param userid the value for logaspect.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logaspect.messs
     *
     * @return the value of logaspect.messs
     *
     * @mbg.generated
     */
    public String getMesss() {
        return messs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logaspect.messs
     *
     * @param messs the value for logaspect.messs
     *
     * @mbg.generated
     */
    public void setMesss(String messs) {
        this.messs = messs == null ? null : messs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logaspect.time
     *
     * @return the value of logaspect.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logaspect.time
     *
     * @param time the value for logaspect.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}