package com.neuedu.dao;

import com.neuedu.pojo.Logaspect;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface LogaspectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logaspect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logaspect
     *
     * @mbg.generated
     */
    int insert(Logaspect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logaspect
     *
     * @mbg.generated
     */
    Logaspect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logaspect
     *
     * @mbg.generated
     */
    List<Logaspect> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logaspect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Logaspect record);
}