package com.neuedu.dao;

import com.neuedu.pojo.Userorder;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface UserorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorder
     *
     * @mbg.generated
     */
    int insert(Userorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorder
     *
     * @mbg.generated
     */
    Userorder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorder
     *
     * @mbg.generated
     */
    List<Userorder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userorder record);
}