package com.neuedu.dao;

import com.neuedu.pojo.Userorderitem;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface UserorderitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorderitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorderitem
     *
     * @mbg.generated
     */
    int insert(Userorderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorderitem
     *
     * @mbg.generated
     */
    Userorderitem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorderitem
     *
     * @mbg.generated
     */
    List<Userorderitem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userorderitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userorderitem record);
}